import type { Metadata } from "next";
import Script from "next/script";

// import global css file
import "./globals.css";
// import bootstrap css
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./utils/BootstrapClient";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<BootstrapClient />
				{children}
			</body>
		</html>
	);
}
