import type { Metadata } from "next";
import Script from "next/script";

// import global css file
import "./globals.css";
// import bootstrap css
import "bootstrap/dist/css/bootstrap.min.css";

import BootstrapClient from "./utils/BootstrapClient";

// custom css
import "../public/assets/fonts/css/boxicons.min.css";
import "../public/assets/css/theme.min.css";

// Bootstrap Icons CDN
import "bootstrap-icons/font/bootstrap-icons.min.css";

// Bootstrap Icons CDN
import "bootstrap-icons/font/bootstrap-icons.min.css";

// Layout components
import HeaderWrapper from "./components/HeaderWrapper";
import Footer from "./components/Footer";
import ThemeToggleScript from "./components/ThemeToggleScript";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ThemeToggleScript />
				<BootstrapClient />
				<HeaderWrapper />
				<main>{children}</main>
				<Footer />

				<Script
					src="https://cdnjs.cloudflare.com/ajax/libs/headhesive/1.2.4/headhesive.min.js"
					strategy="beforeInteractive" // or afterInteractive – beforeInteractive loads early
					integrity="sha512-..." // optional: add if you want SRI (check cdnjs for latest hash)
					crossOrigin="anonymous"
				/>
				<Script
					src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
					integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
					crossOrigin="anonymous"
					strategy="afterInteractive"
				/>
				<Script src="/assets/js/theme.min.js" strategy="afterInteractive" />
			</body>
		</html>
	);
}
