import type { Metadata } from "next";
import Script from "next/script";

// import global css file
import "./globals.css";
// import bootstrap css
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./utils/BootstrapClient";

// custom css
import "../public/assets/fonts/css/boxicons.min.css";
import "../public/assets/css/theme.min.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Script src="/assets/js/theme.min.js" strategy="afterInteractive" />
				<BootstrapClient />
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
